export const metadata={
  title:'BLOG',
  description:'BLOG, generated by create next app'
}
import Title from '@/components/pageComponents/Title'

import Link from 'next/link';
import React from 'react'



export const POST = [
  {
    id: 1,
    title: "Post 1",
    slug: "post-1",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 2,
    title: "Post 2",
    slug: "post-2",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 3,
    title: "Post 3",
    slug: "post-3",
    content:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
];


const Blog = () => {
  return (
   <>
     <Title title='BLOG'/>
      <main className="container mx-auto">
        <div className="grid gap-5">
          {
            POST.map((item)=>(
              <div key={item.id} className='shadow rounded-md p-5'>
                <h2 className='text-2xl front-blod'>
                  {item.title}
                </h2>
                <Link href={`/blog/${item.slug}`}>Mas info</Link>
              </div>
            ))
          }
        </div>
      </main> 
    </>

  )
}

export default Blog